# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csuser/Desktop/450/hw3-sblevens

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csuser/Desktop/450/hw3-sblevens

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csuser/Desktop/450/hw3-sblevens/CMakeFiles /home/csuser/Desktop/450/hw3-sblevens/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csuser/Desktop/450/hw3-sblevens/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hw3_tests

# Build rule for target.
hw3_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3_tests
.PHONY : hw3_tests

# fast build rule for target.
hw3_tests/fast:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/build
.PHONY : hw3_tests/fast

#=============================================================================
# Target rules for targets named hw3_examples

# Build rule for target.
hw3_examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hw3_examples
.PHONY : hw3_examples

# fast build rule for target.
hw3_examples/fast:
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/build
.PHONY : hw3_examples/fast

adjacency_list.o: adjacency_list.cpp.o

.PHONY : adjacency_list.o

# target to build an object file
adjacency_list.cpp.o:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/adjacency_list.cpp.o
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/adjacency_list.cpp.o
.PHONY : adjacency_list.cpp.o

adjacency_list.i: adjacency_list.cpp.i

.PHONY : adjacency_list.i

# target to preprocess a source file
adjacency_list.cpp.i:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/adjacency_list.cpp.i
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/adjacency_list.cpp.i
.PHONY : adjacency_list.cpp.i

adjacency_list.s: adjacency_list.cpp.s

.PHONY : adjacency_list.s

# target to generate assembly for a file
adjacency_list.cpp.s:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/adjacency_list.cpp.s
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/adjacency_list.cpp.s
.PHONY : adjacency_list.cpp.s

adjacency_matrix.o: adjacency_matrix.cpp.o

.PHONY : adjacency_matrix.o

# target to build an object file
adjacency_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/adjacency_matrix.cpp.o
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/adjacency_matrix.cpp.o
.PHONY : adjacency_matrix.cpp.o

adjacency_matrix.i: adjacency_matrix.cpp.i

.PHONY : adjacency_matrix.i

# target to preprocess a source file
adjacency_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/adjacency_matrix.cpp.i
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/adjacency_matrix.cpp.i
.PHONY : adjacency_matrix.cpp.i

adjacency_matrix.s: adjacency_matrix.cpp.s

.PHONY : adjacency_matrix.s

# target to generate assembly for a file
adjacency_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/adjacency_matrix.cpp.s
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/adjacency_matrix.cpp.s
.PHONY : adjacency_matrix.cpp.s

graph.o: graph.cpp.o

.PHONY : graph.o

# target to build an object file
graph.cpp.o:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/graph.cpp.o
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/graph.cpp.o
.PHONY : graph.cpp.o

graph.i: graph.cpp.i

.PHONY : graph.i

# target to preprocess a source file
graph.cpp.i:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/graph.cpp.i
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/graph.cpp.i
.PHONY : graph.cpp.i

graph.s: graph.cpp.s

.PHONY : graph.s

# target to generate assembly for a file
graph.cpp.s:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/graph.cpp.s
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/graph.cpp.s
.PHONY : graph.cpp.s

hw3_examples.o: hw3_examples.cpp.o

.PHONY : hw3_examples.o

# target to build an object file
hw3_examples.cpp.o:
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/hw3_examples.cpp.o
.PHONY : hw3_examples.cpp.o

hw3_examples.i: hw3_examples.cpp.i

.PHONY : hw3_examples.i

# target to preprocess a source file
hw3_examples.cpp.i:
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/hw3_examples.cpp.i
.PHONY : hw3_examples.cpp.i

hw3_examples.s: hw3_examples.cpp.s

.PHONY : hw3_examples.s

# target to generate assembly for a file
hw3_examples.cpp.s:
	$(MAKE) -f CMakeFiles/hw3_examples.dir/build.make CMakeFiles/hw3_examples.dir/hw3_examples.cpp.s
.PHONY : hw3_examples.cpp.s

hw3_tests.o: hw3_tests.cpp.o

.PHONY : hw3_tests.o

# target to build an object file
hw3_tests.cpp.o:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/hw3_tests.cpp.o
.PHONY : hw3_tests.cpp.o

hw3_tests.i: hw3_tests.cpp.i

.PHONY : hw3_tests.i

# target to preprocess a source file
hw3_tests.cpp.i:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/hw3_tests.cpp.i
.PHONY : hw3_tests.cpp.i

hw3_tests.s: hw3_tests.cpp.s

.PHONY : hw3_tests.s

# target to generate assembly for a file
hw3_tests.cpp.s:
	$(MAKE) -f CMakeFiles/hw3_tests.dir/build.make CMakeFiles/hw3_tests.dir/hw3_tests.cpp.s
.PHONY : hw3_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hw3_tests"
	@echo "... hw3_examples"
	@echo "... adjacency_list.o"
	@echo "... adjacency_list.i"
	@echo "... adjacency_list.s"
	@echo "... adjacency_matrix.o"
	@echo "... adjacency_matrix.i"
	@echo "... adjacency_matrix.s"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... hw3_examples.o"
	@echo "... hw3_examples.i"
	@echo "... hw3_examples.s"
	@echo "... hw3_tests.o"
	@echo "... hw3_tests.i"
	@echo "... hw3_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

